version: "3.9"

services:
  postgres:
    image: postgres:16.4
    container_name: effective_mobile_subscription_service_postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - my_custom_network

  effective_mobile_subscription_service:
    image: effective-mobile-subscription-service:latest
    container_name: effective_mobile_subscription_service_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      GRPC_PORT: "${GRPC_PORT}"
      HTTP_PORT: "${HTTP_PORT}"
    restart: unless-stopped
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
